#!/bin/sh -e

if [ $# -eq 0 ]; then
   echo "$0 requires at least one argument." 1>&2
   echo "Usage: $0 files-to-indent" 1>&2
   exit 1
fi

while [ $# -ge 1 ]
do
   if [ -d $1 ]; then
      echo "Argument of $0 $1 cannot be a directory." 1>&2
      exit 1
   fi
   if [ ! -e $1 ]; then
      echo "$0: $1 not found." 1>&2
      exit 1
   fi
   echo "Indenting $1 with emacs in batch mode"
   emacs -batch $1 -l ~/emacs-global-indent-file -f emacs-global-indent
   echo
   shift
done
